### ISSUE TITLE
Make multiple webhooks with diffrent filters

### ISSUE THREAD

**Issue by naleyjanhelge** [jinxrat/discordance#2]
Hi!

Love your plugin and it is very easy to use. I do however have a feature request. I want to have multiple webhooks to my site.

Example I have an FAQ on my Discord server. I then want to publish new posts with the category FAQ in this channel.

I do also have news post on my website. Theese have a post catgory called News. I then want theese to publish in my News channel on Discord.

Hope this makes sense. Thanks again for a great plugin.

Alternative is that I can have a diffrent webhook for every post type. Then I can just make my FAQ a custom post type.

**Comment by jinxrat** [comment]
this is in the plans for v0.3.0, soon.
